import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import Web3 from 'web3'

const ConnectWalletButton = styled.button`
background: #784ffe;
color: #fff;
padding: 0 32px;
height: 54px;
line-height: 54px;

:hover {
    box-shadow: 0 0 0 4px rgba(120,79,254,.5);
}
`

export default function Home() {
  
  const web3 = new Web3("https://bsc-dataseed.binance.org/" || "ws://localhost:8545");

  const onWalletConnectClick = (e) =>  {
    e.preventDefault();
    console.log('Fetching web3 info...');
    
    web3.eth.getChainId().then(console.log);
    web3.eth.getNodeInfo().then(console.log);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <ConnectWalletButton onClick={onWalletConnectClick}>Connect Wallet</ConnectWalletButton>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
